### ISSUE TITLE
error when running ./MOT16_eval/eval.sh

### ISSUE THREAD

**Issue by ConstantSun** [mikel-brostrom/Yolov5_DeepSort_Pytorch#108]
I just $ git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git and install requirement , run the bash script: $  ./MOT16_eval/eval.sh . However, I got the error: 
```bash 
no seqmap found: /home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/gt/mot_challenge/seqmaps/MOT16-train.txt
Traceback (most recent call last):
  File "/home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 82, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "/home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 158, in _get_seq_info
    raise TrackEvalException('no seqmap found: ' + os.path.basename(seqmap_file))
trackeval.utils.TrackEvalException: no seqmap found: MOT16-train.txt

```

**Comment by mikel-brostrom** [comment]
I made a small modification to `eval.sh`.

I suggest you to start from a clean slate:

`$ git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

install requirements.txt and then run:

`$ ./MOT16_eval/eval.sh`

Let me know if it now works for you

**Comment by ConstantSun** [comment]
After redoing as your suggestion,
I got **CUDA error: out of memory**
```bash
Traceback (most recent call last):
  File "track.py", line 277, in <module>
    detect(args)                                                                                                                                              File "track.py", line 91, in detect
    deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
  File "/data.local/hangd/new/Yolov5_DeepSort_Pytorch/deep_sort_pytorch/deep_sort/deep_sort.py", line 18, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "/data.local/hangd/new/Yolov5_DeepSort_Pytorch/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 14, in __init__
    state_dict = torch.load(model_path, map_location=torch.device(self.device))[
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/serialization.py", line 827, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/serialization.py", line 155, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/hangd/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 528, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

and this err:

```bash
Traceback (most recent call last):
  File "track.py", line 277, in <module>
    detect(args)
  File "track.py", line 127, in detect
    dataset = LoadImages(source, img_size=imgsz)
  File "/data.local/hangd/new/Yolov5_DeepSort_Pytorch/yolov5/utils/datasets.py", line 132, in __init__
    raise Exception(f'ERROR: {p} does not exist')
Exception: ERROR: /home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train/MOT16-02/MOT16-02 does not exist
mv: cannot stat '/home/hangd/Yolov5_DeepSort_Pytorch/inference/output/MOT16-02.txt': No such file or directory
Inference on all MOT16 sequences DONE
```
and also this error:
```bash
no seqmap found: /home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/gt/mot_challenge/seqmaps/MOT16-train.txt
Traceback (most recent call last):
  File "/home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 82, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "/home/hangd/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 158, in _get_seq_info
    raise TrackEvalException('no seqmap found: ' + os.path.basename(seqmap_file))
trackeval.utils.TrackEvalException: no seqmap found: MOT16-train.txt
```

**Comment by mikel-brostrom** [comment]
Notice this line of code in eval.sh:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/d1ad253908a672362deed19780662a948eb0568b/MOT16_eval/eval.sh#L68

It specifies the number of parallel MOT16 sequence inference streams that you run on you GPU. However, this hardcoded value suits a 4GB GPU, feel free to lower N, in order to be able to run it on your specific hardware setup.

**Comment by ConstantSun** [comment]
It's so weird, I'm using a server with RTX 2080Ti with 10GB RAM.

**Comment by ConstantSun** [comment]
Oh, I think I got my problem. My often working path in my server is /data.local/hangd/Yolov5_DeepSort_Pytorch , however running this kind of script 
```bash
! -d ~/Yolov5_DeepSort_Pytorch/blah_blah
```
makes my path is /home/hangd/Yolov5_DeepSort_Pytorch/
All i need is to change 
```bash
! -d ~/Yolov5_DeepSort_Pytorch/blah_blah
```
to
```bash
! -d  /data.local/hangd/Yolov5_DeepSort_Pytorch/blah_blah
```

**Comment by jyothirrose** [comment]
> Oh, I think I got my problem. My often working path in my server is /data.local/hangd/Yolov5_DeepSort_Pytorch , however running this kind of script
> 
> ```shell
> ! -d ~/Yolov5_DeepSort_Pytorch/blah_blah
> ```
> 
> makes my path is /home/hangd/Yolov5_DeepSort_Pytorch/ All i need is to change
> 
> ```shell
> ! -d ~/Yolov5_DeepSort_Pytorch/blah_blah
> ```
> 
> to
> 
> ```shell
> ! -d  /data.local/hangd/Yolov5_DeepSort_Pytorch/blah_blah
> ```

still have the issue while evaluating
