### ISSUE TITLE
Error due to  'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

### ISSUE THREAD

**Issue by regviray** [mikel-brostrom/Yolov5_DeepSort_Pytorch#175]
Hello there,

I think the most recent update 'broke' the inference track.py script per the output below.  This can even be experienced running the 'Run inference on video' section using the Google Colab provided as a reference @ https://colab.research.google.com/drive/18nIqkBr68TkK8dHdarxTco6svHUJGggY?usp=sharing#scrollTo=oqIP5shr9HQd

I was able to get the tracker running by manually downloading the 'ckpt.t7' file, dropping it in the referenced directory deep_sort_pytorch/deep_sort/deep/checkpoint/' and running.

Traceback (most recent call last):
  File "track.py", line 216, in <module>
    detect(args)
  File "track.py", line 38, in detect
    use_cuda=True)
  File "/content/Yolov5_DeepSort_Pytorch/Yolov5_DeepSort_Pytorch/deep_sort_pytorch/deep_sort/deep_sort.py", line 17, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "/content/Yolov5_DeepSort_Pytorch/Yolov5_DeepSort_Pytorch/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 14, in __init__
    state_dict = torch.load(model_path, map_location=torch.device(self.device))[
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

**Comment by beebrain** [comment]
I have a same error.

**Comment by beebrain** [comment]
I found the checkpoint weight from
https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6.
I put that file into the checkpoint folder. It works.

**Comment by kentaroy47** [comment]
Me too.
I guess this file can be added to the git to reduce issues.

**Comment by mikel-brostrom** [comment]
Should work now. I forgot to upload ckpt.t7 to the new release. Let me know if this solves the issue!

**Comment by Nivitus** [comment]
Still Not working! What should I do?

**Comment by SzaremehrjardiMT** [comment]
> I found the checkpoint weight from https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6. I put that file into the checkpoint folder. It works.

thanks it works now!
