### ISSUE TITLE
Issue with custom Model

### ISSUE THREAD

**Issue by carlosedubarreto** [mikel-brostrom/Yolov5_DeepSort_Pytorch#218]
Hello. First of all your work is great. And I'm trying to use it with a custom model.

I followed 2 tutorials on creating a model and could even test this model with yolov5 adn didnt receive error, but, when using it with your deep sort implementation it gives me this error.
![image](https://user-images.githubusercontent.com/4061130/141079691-1fd20479-25b1-4004-8048-43cf84c9aada.png)

I'm trying for the last 2 days to solve this, but I cant find where is the problem. Looks like the number of classes is the problem (if I understood it right) because my model has only 4 classes.
I changed this value (from 80 to 4) in many places but there was no difference. I even trained another yolov5 model changing a custom yaml (i saw this on a second tutorial) but nothing different happened.

Can you give me some direction, I'm lost .

here is the text from the print above
```
(tf) D:\deep_learning\Yolov5_DeepSort_Pytorch>python track.py --source ../20211106_110214.mp4 --show-vid --save-vid --yolo_weights best.pt
C:\Users\Pichau\.conda\envs\tf\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1274: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

Traceback (most recent call last):
  File "D:\deep_learning\Yolov5_DeepSort_Pytorch\track.py", line 225, in <module>
    detect(args)
  File "D:\deep_learning\Yolov5_DeepSort_Pytorch\track.py", line 85, in detect
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "C:\Users\Pichau\.conda\envs\tf\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./yolov5\models\yolo.py", line 124, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "./yolov5\models\yolo.py", line 156, in forward_once
    x = m(x)  # run
  File "C:\Users\Pichau\.conda\envs\tf\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./yolov5\models\yolo.py", line 65, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (52) at non-singleton dimension 3
```

**Comment by carlosedubarreto** [comment]
Nevermind, the problem was with me.
Doing the anotation using Roboflow was the best way, I didnt have the error.
thanks a lot for this tool.
