### ISSUE TITLE
When i revise the reid model , the following error occurred.

### ISSUE THREAD

**Issue by mcjqwer** [mikel-brostrom/Yolov5_DeepSort_Pytorch#220]
Traceback (most recent call last):
  File "track.py", line 385, in <module>
    detect(args)
  File "track.py", line 290, in detect
    outputs = deepsort.update(xywhs, confss, im0)
  File "/home/mcj/桌面/yolo5dp_torch/deepsort/deep_sort/deep_sort.py", line 33, in update
    features = self._get_features(bbox_xywh, ori_img)  # 提取特征
  File "/home/mcj/桌面/yolo5dp_torch/deepsort/deep_sort/deep_sort.py", line 144, in _get_features
    features = self.extractor(im_crops)
  File "/home/mcj/桌面/yolo5dp_torch/deepsort/deep_sort/deep/feature_extractor.py", line 246, in __call__
    features = self.net(im_batch)
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcj/桌面/yolo5dp_torch/deepsort/deep_sort/deep/feature_extractor.py", line 203, in forward
    x = self.classifier(x)
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcj/桌面/yolo5dp_torch/deepsort/deep_sort/deep/feature_extractor.py", line 156, in forward
    x = self.add_block(x)
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/functional.py", line 2012, in batch_norm
    _verify_batch_size(input.size())
  File "/home/mcj/anaconda3/envs/torch16gpu/lib/python3.8/site-packages/torch/nn/functional.py", line 1995, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

**Comment by mcjqwer** [comment]
It seems that someone's video will not report an error , and no one's video will report an error!!!

**Comment by gubei528** [comment]
我也遇到了这样的问题

**Comment by gubei528** [comment]
请问有纠正吗
