### ISSUE TITLE
runtime tensor size

### ISSUE THREAD

**Issue by dasaipoom** [mikel-brostrom/Yolov5_DeepSort_Pytorch#222]
when i used custom model it said 
File "P:\YoloV5_sort\Yolov5_DeepSort_Pytorch\./yolov5\models\yolo.py", line 64, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (84) at non-singleton dimension 3

what shold i setting for train a model

**Comment by sunghyun-sptr** [comment]
I get exactly the same error. Need Help!

it causes no error when I train custom data with yolov3, 
but when with yolov5 it causes the error below: 
```
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
100% 755k/755k [00:00<00:00, 18.2MB/s]
Downloading https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/releases/download/v3.0/ckpt.t7 to deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7...
100% 43.9M/43.9M [00:00<00:00, 117MB/s]

/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "track.py", line 225, in <module>
    detect(args)
  File "track.py", line 85, in detect
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 123, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "./yolov5/models/yolo.py", line 155, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 64, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (84) at non-singleton dimension 3
```

**Comment by sunghyun-sptr** [comment]
Oh I found the comment that could help:
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/216#issuecomment-965799964

**Comment by mikel-brostrom** [comment]
Pull and try again.
