### ISSUE TITLE
UnboundLocalError: local variable 't5' referenced before assignment

### ISSUE THREAD

**Issue by totoadel** [mikel-brostrom/Yolov5_DeepSort_Pytorch#270]
```
Fusing layers...
Model Summary: 444 layers, 86705005 parameters, 0 gradients
Traceback (most recent call last):
  File "track.py", line 258, in <module>
    detect(opt)
  File "track.py", line 192, in detect
    LOGGER.info(f'{s}Done. YOLO:({t3 - t2:.3f}s), DeepSort:({t5 - t4:.3f}s)')
UnboundLocalError: local variable 't5' referenced before assignment
```

**Comment by mikel-brostrom** [comment]
This should be fixed now! Let me know if it works for you

**Comment by totoadel** [comment]
it works ,Thank You.
i have a Request< can you add the speed estimated to the repo please>.
