### ISSUE TITLE
 No such file or directory: 'yolov5/weights/best.pt'

### ISSUE THREAD

**Issue by shadfien** [mikel-brostrom/Yolov5_DeepSort_Pytorch#278]
Hi,
      I have a problem that hasn't been solved for several days. Please consult.
      An error is reported after i changed the weight name in the detector.launch folder, i put best.pt into right  location,but it can't  normal run.
     but it can run using yolov5s.pt.

```
[INFO] [1642147902.434877]: Found weights, loading /home/ricardo/catkin_ws1/src/yolov5_deepsort_ros/scripts/yolov5/weights/best.pt
Traceback (most recent call last):
  File "/home/ricardo/catkin_ws1/src/yolov5_deepsort_ros/scripts/detector.py", line 227, in <module>
    dm = DetectorManager()
  File "/home/ricardo/catkin_ws1/src/yolov5_deepsort_ros/scripts/detector.py", line 55, in __init__
    self.model = attempt_load(weights_name, map_location=device)  # load FP32 model
  File "/home/ricardo/anaconda3/envs/yolo/lib/python3.7/site-packages/yolov5/models/experimental.py", line 97, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/ricardo/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ricardo/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ricardo/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'yolov5/weights/best.pt
```

**Comment by mikel-brostrom** [comment]
I cannot help you on your custom version of this repo (I can see in the error that the folder structure isn't matching the original repo) as I don't have enough information to be able to give you any valuable advice

**Comment by junying101** [comment]
> May I ask if you have solved this problem? I also encountered this difficulty when training yolov8 recently. Looking forward to your reply, thank you.
