### ISSUE TITLE
Run track for sequence of images

### ISSUE THREAD

**Issue by ArthurHakobyann** [mikel-brostrom/Yolov5_DeepSort_Pytorch#291]
How can I run track.py on sequence of images? All images in one folder.
`python track.py --source C:\data`
`C:\data` is folder path 
But I get this error 
```
image 1/131 C:\data\0000000000.png: 256x640 2 cars, Done. YOLO:(0.154s), DeepSort:(0.032s)
image 2/131 C:\data\0000000001.png: 256x640 2 cars, Done. YOLO:(0.149s), DeepSort:(0.032s)
Traceback (most recent call last):
  File "track.py", line 258, in <module>
    detect(opt)
  File "track.py", line 184, in detect
    with open(txt_path, 'a') as f:
OSError: [Errno 22] Invalid argument: 'runs\\track\\exp8/C:\data.txt'
```

**Comment by mikel-brostrom** [comment]
This piece of software has never been tested on windows. Feel free to leave a PR if you find a fix for this!
