### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by yunfengsay** [mikel-brostrom/Yolov5_DeepSort_Pytorch#71]
```bash
Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.4, config_deepsort='deep_sort_pytorch/configs/deep_sort.yaml', device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='0', view_img=False, weights='yolov5/weights/yolov5s.pt')
/home/yunfeng/code/Yolov5_DeepSort_Pytorch/deep_sort_pytorch/utils/parser.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
Traceback (most recent call last):
  File "track.py", line 263, in <module>
    detect(args)
  File "track.py", line 88, in detect
    model = torch.load(weights, map_location=device)[
  File "/home/yunfeng/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/yunfeng/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
```
pytorch version **1.7.1**

**Comment by yunfengsay** [comment]
weights Incomplete download
