### ISSUE TITLE
python track.py --source Error

### ISSUE THREAD

**Issue by pikaqiuEric** [mikel-brostrom/Yolov5_DeepSort_Pytorch#94]
when i want to run this code,the environment is windows .i get the error 
 if self.inplace:
  File "E:\Anaconda\envs\python38\lib\site-packages\torch\nn\modules\module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Detect' object has no attribute 'inplace'
i guess the reason is that Model does not match weight.Can you give you how can I get?

**Comment by mikel-brostrom** [comment]
Make sure that ALL the requirements are fulfilled: Python >= 3.8, PyTorch >= 1.6 etc.
Then make sure both your code and models are up to date. If in doubt, simply start from a clean slate: reclone the repo and download new weights

**Comment by tobyerbailey** [comment]
I have had the same problem even after re-cloning  a fresh version with recursive submodule population. I have confirmed I have appropriate versions as per the requirements for all pip modules.

If I cd into the yolov5 directory and run a detect it grabs the weights using download.sh and works. If I then copy those weights to the expected location yolov5/weights and try to run the track.py I get the same in place error:

```
Traceback (most recent call last):
  File "track.py", line 263, in <module>
    detect(args)
  File "track.py", line 126, in detect
    pred = model(img, augment=opt.augment)[0]
  File "/Users/me/.pyenv/versions/deep_sort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 117, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "./yolov5/models/yolo.py", line 148, in forward_once
    x = m(x)  # run
  File "/Users/me/.pyenv/versions/deep_sort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 55, in forward
    if self.inplace:
  File "/Users/me/.pyenv/versions/deep_sort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'inplace'
```

**Comment by mikel-brostrom** [comment]
I adapted the way of loading the model to the new Yolov5 standard (from torch.load to yolov5.utils.general.attempt_loading).
Let me know if this solves your problems

**Comment by tobyerbailey** [comment]
Fixed for me...thank you very much!
